version: "2.3"
services:
  servers-manager:
    build: .
    container_name: ServersManager
    volumes:
      - ./server-types:/servers/server-types
      - ./usual-plugins:/servers/usual-plugins
      - ./tmp:/servers/tmp
      - /var/run/docker.sock:/var/run/docker.sock # allow the docker to start other dockers
    ports:
      - "8000:8000"
    environment:
      - MACHINE_IP=${MACHINE_IP}
      - PUBLIC_IP=${PUBLIC_IP}
      - PARENT_PWD=${PARENT_PWD}
      - SERVER_PATH_SHIFT=${SERVER_PATH_SHIFT}
    #restart: unless-stopped